# Generated by ChatGPT on 2025-09-20
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Procedure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("steps", models.JSONField(default=list)),
                ("instruments", models.JSONField(default=list)),
                ("zones", models.JSONField(default=dict)),
                ("checklist", models.JSONField(default=list)),
                ("rubric", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("IN_PROGRESS", "In progress"), ("COMPLETED", "Completed")],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("score_total", models.FloatField(blank=True, null=True)),
                ("subscores", models.JSONField(blank=True, default=dict)),
                ("feedback", models.JSONField(blank=True, default=list)),
                ("algorithm_version", models.CharField(default="v1", max_length=20)),
                (
                    "procedure",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="simulator.procedure"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField(default=dict)),
                ("timestamp_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="simulator.attempt"
                    ),
                ),
            ],
        ),
    ]
