# Generated by ChatGPT on 2025-09-20
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedure",
            name="difficulty",
            field=models.CharField(default="Intermedia", max_length=50),
        ),
        migrations.AddField(
            model_name="procedure",
            name="duration_estimated_minutes",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="procedure",
            name="is_playable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="procedure",
            name="procedure_type",
            field=models.CharField(default="Abierta", max_length=50),
        ),
        migrations.AddField(
            model_name="procedure",
            name="prompt_base",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="procedure",
            name="specialty",
            field=models.CharField(default="General", max_length=120),
        ),
        migrations.AddField(
            model_name="attempt",
            name="ai_feedback",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="attempt",
            name="ai_model",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="attempt",
            name="ai_provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="attempt",
            name="ai_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attempt",
            name="score_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
