# Generated by ChatGPT on 2025-09-20
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(
                        choices=[("OPENAI", "OpenAI"), ("GEMINI", "Gemini")],
                        default="OPENAI",
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(default="gpt-4o-mini", max_length=120)),
                ("api_key_encrypted", models.TextField(blank=True)),
                ("use_ai", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_settings",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
    ]
